include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "test/**/*.mock.dart"

linter:
  rules:
    prefer_single_quotes: true
    unnecessary_const: true
    avoid_print: true
