import 'dart:async' show unawaited;
import 'dart:ui' show PlatformDispatcher;

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'app.dart';
import 'core/db/app_database.dart';
import 'core/services/system_integration_service.dart';
import 'data/cloud/cloud_gateway.dart';
import 'data/repositories/providers.dart';
import 'data/repositories/goal_repository.dart';
import 'features/bootstrap/bootstrap_error_screen.dart';

/// Half-opened database from a failed bootstrap attempt (closed on retry so
/// a restart never accumulates leaked isolates/file handles).
AppDatabase? _lastOpenedDb;

/// Crash-proof entry point (zero-white-screen guarantee): ANY failure in the
/// pre-runApp bootstrap (DB open, SQLCipher, Keystore, prefs) previously left
/// the app on a dead white surface because no first frame was ever produced.
/// Now every failure path still renders a themed BootstrapErrorApp with the
/// reason + Retry.
Future<void> main() => bootstrapAndRun();

/// Runs the offline-first bootstrap and renders the app; on any error,
/// renders [BootstrapErrorApp] instead. Safe to re-run (Retry).
Future<void> bootstrapAndRun() async {
  WidgetsFlutterBinding.ensureInitialized();
  _installGlobalErrorHandlers();

  // Portrait-first gaming dashboard (§4: Glanceable 360–480dp).
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  try {
    // Retry after a failed attempt: close the half-opened DB first.
    await _lastOpenedDb?.close();
    _lastOpenedDb = null;

  // Bootstrap: user data opens locally (Drift); prices/search are online-only.
  final db = await openRealDatabase();
    _lastOpenedDb = db;
    await bootstrapDatabase(db);
    final prefs = await SharedPreferences.getInstance();

    CloudGateway gateway = LocalOnlyGateway();
    try {
      // Production binding: firebase_options.dart generated by
      // `flutterfire configure` (§3). Absent config → stay local-only.
      await Firebase.initializeApp();
      gateway = FirebaseGateway(initialized: true);
    } catch (_) {
      // No google-services.json / no network → offline-first default.
      gateway = LocalOnlyGateway();
    }

    final onboarded = prefs.getBool('nv_onboarded') ?? false;

    runApp(
      ProviderScope(
        overrides: [
          dbProvider.overrideWithValue(db),
          cloudGatewayProvider.overrideWithValue(gateway),
          onboardedProvider.overrideWith((ref) => onboarded),
        ],
        child: const NeoVaultApp(),
      ),
    );

    // (7) App Shortcuts + (6) Interactive Notifications + (4/5) Home Widget.
    // These are best-effort and must never block the UI launch.
    unawaited(SystemIntegrationService.initStandalone());
  } catch (e, st) {
    debugPrint('NV bootstrap failed: $e\n$st');
    runApp(BootstrapErrorApp(error: e, onRetry: bootstrapAndRun));
  }
}

/// Global handlers: uncaught async errors and build errors are logged
/// (and rendered readably via ErrorWidget.builder) instead of silently
/// producing a blank surface — critical for release builds.
void _installGlobalErrorHandlers() {
  FlutterError.onError = (details) {
    FlutterError.presentError(details);
  };
  PlatformDispatcher.instance.onError = (e, st) {
    debugPrint('NV uncaught platform error: $e\n$st');
    return true;
  };
  ErrorWidget.builder = (details) => _NvCrashPlaceholder(details: details);
}

/// Readable in-place error widget (replaces the default grey/red stripes).
class _NvCrashPlaceholder extends StatelessWidget {
  const _NvCrashPlaceholder({required this.details});

  final FlutterErrorDetails details;

  @override
  Widget build(BuildContext context) {
    final summary = details.exception.toString();
    return Container(
      color: const Color(0xFF161618),
      alignment: Alignment.center,
      padding: const EdgeInsets.all(24),
      child: SingleChildScrollView(
        child: Text(
          'NeoVault error:\n$summary',
          style: const TextStyle(
            color: Color(0xFFD9707A),
            fontSize: 12,
            fontFamily: 'monospace',
          ),
        ),
      ),
    );
  }
}

/// Exposed for tests/CI smoke-run.
@visibleForTesting
Future<void> bootstrapForTesting(ProviderContainer container) async {
  await container.read(goalRepositoryProvider).rawStats();
}
